// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: kruise_game_api.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetGameServersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filter string `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
}

func (x *GetGameServersRequest) Reset() {
	*x = GetGameServersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kruise_game_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGameServersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameServersRequest) ProtoMessage() {}

func (x *GetGameServersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kruise_game_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameServersRequest.ProtoReflect.Descriptor instead.
func (*GetGameServersRequest) Descriptor() ([]byte, []int) {
	return file_kruise_game_api_proto_rawDescGZIP(), []int{0}
}

func (x *GetGameServersRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

type GetGameServersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameServers []string `protobuf:"bytes,1,rep,name=game_servers,json=gameServers,proto3" json:"game_servers,omitempty"`
}

func (x *GetGameServersResponse) Reset() {
	*x = GetGameServersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kruise_game_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGameServersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameServersResponse) ProtoMessage() {}

func (x *GetGameServersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kruise_game_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameServersResponse.ProtoReflect.Descriptor instead.
func (*GetGameServersResponse) Descriptor() ([]byte, []int) {
	return file_kruise_game_api_proto_rawDescGZIP(), []int{1}
}

func (x *GetGameServersResponse) GetGameServers() []string {
	if x != nil {
		return x.GameServers
	}
	return nil
}

type UpdateGameServersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filter    string `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	JsonPatch string `protobuf:"bytes,2,opt,name=json_patch,json=jsonPatch,proto3" json:"json_patch,omitempty"`
}

func (x *UpdateGameServersRequest) Reset() {
	*x = UpdateGameServersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kruise_game_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateGameServersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGameServersRequest) ProtoMessage() {}

func (x *UpdateGameServersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kruise_game_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGameServersRequest.ProtoReflect.Descriptor instead.
func (*UpdateGameServersRequest) Descriptor() ([]byte, []int) {
	return file_kruise_game_api_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateGameServersRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *UpdateGameServersRequest) GetJsonPatch() string {
	if x != nil {
		return x.JsonPatch
	}
	return ""
}

type UpdateGameServersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*UpdateGameServerResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *UpdateGameServersResponse) Reset() {
	*x = UpdateGameServersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kruise_game_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateGameServersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGameServersResponse) ProtoMessage() {}

func (x *UpdateGameServersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kruise_game_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGameServersResponse.ProtoReflect.Descriptor instead.
func (*UpdateGameServersResponse) Descriptor() ([]byte, []int) {
	return file_kruise_game_api_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateGameServersResponse) GetResults() []*UpdateGameServerResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type UpdateGameServerResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameServer        string  `protobuf:"bytes,1,opt,name=game_server,json=gameServer,proto3" json:"game_server,omitempty"`
	UpdatedGameServer string  `protobuf:"bytes,2,opt,name=updated_game_server,json=updatedGameServer,proto3" json:"updated_game_server,omitempty"`
	Error             *string `protobuf:"bytes,3,opt,name=error,proto3,oneof" json:"error,omitempty"`
}

func (x *UpdateGameServerResult) Reset() {
	*x = UpdateGameServerResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kruise_game_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateGameServerResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGameServerResult) ProtoMessage() {}

func (x *UpdateGameServerResult) ProtoReflect() protoreflect.Message {
	mi := &file_kruise_game_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGameServerResult.ProtoReflect.Descriptor instead.
func (*UpdateGameServerResult) Descriptor() ([]byte, []int) {
	return file_kruise_game_api_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateGameServerResult) GetGameServer() string {
	if x != nil {
		return x.GameServer
	}
	return ""
}

func (x *UpdateGameServerResult) GetUpdatedGameServer() string {
	if x != nil {
		return x.UpdatedGameServer
	}
	return ""
}

func (x *UpdateGameServerResult) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type DeleteGameServersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filter string `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
}

func (x *DeleteGameServersRequest) Reset() {
	*x = DeleteGameServersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kruise_game_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteGameServersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGameServersRequest) ProtoMessage() {}

func (x *DeleteGameServersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kruise_game_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGameServersRequest.ProtoReflect.Descriptor instead.
func (*DeleteGameServersRequest) Descriptor() ([]byte, []int) {
	return file_kruise_game_api_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteGameServersRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

type DeleteGameServersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*DeleteGameServerResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *DeleteGameServersResponse) Reset() {
	*x = DeleteGameServersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kruise_game_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteGameServersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGameServersResponse) ProtoMessage() {}

func (x *DeleteGameServersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kruise_game_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGameServersResponse.ProtoReflect.Descriptor instead.
func (*DeleteGameServersResponse) Descriptor() ([]byte, []int) {
	return file_kruise_game_api_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteGameServersResponse) GetResults() []*DeleteGameServerResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type DeleteGameServerResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameServer string  `protobuf:"bytes,1,opt,name=game_server,json=gameServer,proto3" json:"game_server,omitempty"`
	Error      *string `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
}

func (x *DeleteGameServerResult) Reset() {
	*x = DeleteGameServerResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kruise_game_api_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteGameServerResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGameServerResult) ProtoMessage() {}

func (x *DeleteGameServerResult) ProtoReflect() protoreflect.Message {
	mi := &file_kruise_game_api_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGameServerResult.ProtoReflect.Descriptor instead.
func (*DeleteGameServerResult) Descriptor() ([]byte, []int) {
	return file_kruise_game_api_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteGameServerResult) GetGameServer() string {
	if x != nil {
		return x.GameServer
	}
	return ""
}

func (x *DeleteGameServerResult) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type GetGameServerSetsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filter string `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
}

func (x *GetGameServerSetsRequest) Reset() {
	*x = GetGameServerSetsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kruise_game_api_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGameServerSetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameServerSetsRequest) ProtoMessage() {}

func (x *GetGameServerSetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kruise_game_api_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameServerSetsRequest.ProtoReflect.Descriptor instead.
func (*GetGameServerSetsRequest) Descriptor() ([]byte, []int) {
	return file_kruise_game_api_proto_rawDescGZIP(), []int{8}
}

func (x *GetGameServerSetsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

type GetGameServerSetsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameServerSets []string `protobuf:"bytes,1,rep,name=game_server_sets,json=gameServerSets,proto3" json:"game_server_sets,omitempty"`
}

func (x *GetGameServerSetsResponse) Reset() {
	*x = GetGameServerSetsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kruise_game_api_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGameServerSetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameServerSetsResponse) ProtoMessage() {}

func (x *GetGameServerSetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kruise_game_api_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameServerSetsResponse.ProtoReflect.Descriptor instead.
func (*GetGameServerSetsResponse) Descriptor() ([]byte, []int) {
	return file_kruise_game_api_proto_rawDescGZIP(), []int{9}
}

func (x *GetGameServerSetsResponse) GetGameServerSets() []string {
	if x != nil {
		return x.GameServerSets
	}
	return nil
}

type UpdateGameServerSetsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filter    string `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	JsonPatch string `protobuf:"bytes,2,opt,name=json_patch,json=jsonPatch,proto3" json:"json_patch,omitempty"`
}

func (x *UpdateGameServerSetsRequest) Reset() {
	*x = UpdateGameServerSetsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kruise_game_api_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateGameServerSetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGameServerSetsRequest) ProtoMessage() {}

func (x *UpdateGameServerSetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kruise_game_api_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGameServerSetsRequest.ProtoReflect.Descriptor instead.
func (*UpdateGameServerSetsRequest) Descriptor() ([]byte, []int) {
	return file_kruise_game_api_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateGameServerSetsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *UpdateGameServerSetsRequest) GetJsonPatch() string {
	if x != nil {
		return x.JsonPatch
	}
	return ""
}

type UpdateGameServerSetsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*UpdateGameServerSetResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *UpdateGameServerSetsResponse) Reset() {
	*x = UpdateGameServerSetsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kruise_game_api_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateGameServerSetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGameServerSetsResponse) ProtoMessage() {}

func (x *UpdateGameServerSetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kruise_game_api_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGameServerSetsResponse.ProtoReflect.Descriptor instead.
func (*UpdateGameServerSetsResponse) Descriptor() ([]byte, []int) {
	return file_kruise_game_api_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateGameServerSetsResponse) GetResults() []*UpdateGameServerSetResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type UpdateGameServerSetResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameServerSet        string  `protobuf:"bytes,1,opt,name=game_server_set,json=gameServerSet,proto3" json:"game_server_set,omitempty"`
	UpdatedGameServerSet string  `protobuf:"bytes,2,opt,name=updated_game_server_set,json=updatedGameServerSet,proto3" json:"updated_game_server_set,omitempty"`
	Error                *string `protobuf:"bytes,3,opt,name=error,proto3,oneof" json:"error,omitempty"`
}

func (x *UpdateGameServerSetResult) Reset() {
	*x = UpdateGameServerSetResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kruise_game_api_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateGameServerSetResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGameServerSetResult) ProtoMessage() {}

func (x *UpdateGameServerSetResult) ProtoReflect() protoreflect.Message {
	mi := &file_kruise_game_api_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGameServerSetResult.ProtoReflect.Descriptor instead.
func (*UpdateGameServerSetResult) Descriptor() ([]byte, []int) {
	return file_kruise_game_api_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateGameServerSetResult) GetGameServerSet() string {
	if x != nil {
		return x.GameServerSet
	}
	return ""
}

func (x *UpdateGameServerSetResult) GetUpdatedGameServerSet() string {
	if x != nil {
		return x.UpdatedGameServerSet
	}
	return ""
}

func (x *UpdateGameServerSetResult) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type DeleteGameServerSetsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filter string `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
}

func (x *DeleteGameServerSetsRequest) Reset() {
	*x = DeleteGameServerSetsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kruise_game_api_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteGameServerSetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGameServerSetsRequest) ProtoMessage() {}

func (x *DeleteGameServerSetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kruise_game_api_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGameServerSetsRequest.ProtoReflect.Descriptor instead.
func (*DeleteGameServerSetsRequest) Descriptor() ([]byte, []int) {
	return file_kruise_game_api_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteGameServerSetsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

type DeleteGameServerSetsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*DeleteGameServerSetResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *DeleteGameServerSetsResponse) Reset() {
	*x = DeleteGameServerSetsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kruise_game_api_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteGameServerSetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGameServerSetsResponse) ProtoMessage() {}

func (x *DeleteGameServerSetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kruise_game_api_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGameServerSetsResponse.ProtoReflect.Descriptor instead.
func (*DeleteGameServerSetsResponse) Descriptor() ([]byte, []int) {
	return file_kruise_game_api_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteGameServerSetsResponse) GetResults() []*DeleteGameServerSetResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type DeleteGameServerSetResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameServerSet string  `protobuf:"bytes,1,opt,name=game_server_set,json=gameServerSet,proto3" json:"game_server_set,omitempty"`
	Error         *string `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
}

func (x *DeleteGameServerSetResult) Reset() {
	*x = DeleteGameServerSetResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kruise_game_api_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteGameServerSetResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGameServerSetResult) ProtoMessage() {}

func (x *DeleteGameServerSetResult) ProtoReflect() protoreflect.Message {
	mi := &file_kruise_game_api_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGameServerSetResult.ProtoReflect.Descriptor instead.
func (*DeleteGameServerSetResult) Descriptor() ([]byte, []int) {
	return file_kruise_game_api_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteGameServerSetResult) GetGameServerSet() string {
	if x != nil {
		return x.GameServerSet
	}
	return ""
}

func (x *DeleteGameServerSetResult) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

var File_kruise_game_api_proto protoreflect.FileDescriptor

var file_kruise_game_api_proto_rawDesc = []byte{
	0x0a, 0x15, 0x6b, 0x72, 0x75, 0x69, 0x73, 0x65, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x61, 0x70,
	0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x6b, 0x72, 0x75, 0x69, 0x73, 0x65, 0x67,
	0x61, 0x6d, 0x65, 0x61, 0x70, 0x69, 0x22, 0x2f, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x47, 0x61, 0x6d,
	0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x22, 0x3b, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x47, 0x61,
	0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x21, 0x0a, 0x0c, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x67, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x73, 0x22, 0x51, 0x0a, 0x18, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x61,
	0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x6a, 0x73, 0x6f, 0x6e,
	0x5f, 0x70, 0x61, 0x74, 0x63, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6a, 0x73,
	0x6f, 0x6e, 0x50, 0x61, 0x74, 0x63, 0x68, 0x22, 0x5c, 0x0a, 0x19, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3f, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x6b, 0x72, 0x75, 0x69, 0x73, 0x65, 0x67, 0x61,
	0x6d, 0x65, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x61, 0x6d, 0x65,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x07, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x73, 0x22, 0x8e, 0x01, 0x0a, 0x16, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x47, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x12, 0x1f, 0x0a, 0x0b, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x67, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x12, 0x2e, 0x0a, 0x13, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x67, 0x61, 0x6d,
	0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x12, 0x19, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x88, 0x01, 0x01, 0x42, 0x08, 0x0a, 0x06,
	0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x32, 0x0a, 0x18, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x47, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x22, 0x5c, 0x0a, 0x19, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3f, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x6b, 0x72, 0x75, 0x69, 0x73,
	0x65, 0x67, 0x61, 0x6d, 0x65, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x47,
	0x61, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52,
	0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x22, 0x5e, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x67, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x12, 0x19, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x88, 0x01, 0x01, 0x42, 0x08,
	0x0a, 0x06, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x32, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x47,
	0x61, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x65, 0x74, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x22, 0x45, 0x0a, 0x19,
	0x47, 0x65, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x65, 0x74,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x10, 0x67, 0x61, 0x6d,
	0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x74, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x0e, 0x67, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53,
	0x65, 0x74, 0x73, 0x22, 0x54, 0x0a, 0x1b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x61, 0x6d,
	0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x65, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x6a, 0x73,
	0x6f, 0x6e, 0x5f, 0x70, 0x61, 0x74, 0x63, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x6a, 0x73, 0x6f, 0x6e, 0x50, 0x61, 0x74, 0x63, 0x68, 0x22, 0x62, 0x0a, 0x1c, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x65, 0x74,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x42, 0x0a, 0x07, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x6b, 0x72, 0x75,
	0x69, 0x73, 0x65, 0x67, 0x61, 0x6d, 0x65, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x65, 0x74, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x22, 0x9f, 0x01,
	0x0a, 0x19, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x53, 0x65, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x26, 0x0a, 0x0f, 0x67,
	0x61, 0x6d, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x67, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x53, 0x65, 0x74, 0x12, 0x35, 0x0a, 0x17, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x67,
	0x61, 0x6d, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x14, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x47, 0x61, 0x6d,
	0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x65, 0x74, 0x12, 0x19, 0x0a, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x88, 0x01, 0x01, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22,
	0x35, 0x0a, 0x1b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x53, 0x65, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x22, 0x62, 0x0a, 0x1c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x47, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x65, 0x74, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x42, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x6b, 0x72, 0x75, 0x69, 0x73, 0x65,
	0x67, 0x61, 0x6d, 0x65, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x47, 0x61,
	0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x65, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x22, 0x68, 0x0a, 0x19, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x65,
	0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x26, 0x0a, 0x0f, 0x67, 0x61, 0x6d, 0x65, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0d, 0x67, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x65, 0x74, 0x12,
	0x19, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00,
	0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x88, 0x01, 0x01, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x32, 0xc2, 0x02, 0x0a, 0x11, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5d, 0x0a, 0x0e, 0x47, 0x65,
	0x74, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x12, 0x24, 0x2e, 0x6b,
	0x72, 0x75, 0x69, 0x73, 0x65, 0x67, 0x61, 0x6d, 0x65, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74,
	0x47, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x25, 0x2e, 0x6b, 0x72, 0x75, 0x69, 0x73, 0x65, 0x67, 0x61, 0x6d, 0x65, 0x61,
	0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x66, 0x0a, 0x11, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x12, 0x27,
	0x2e, 0x6b, 0x72, 0x75, 0x69, 0x73, 0x65, 0x67, 0x61, 0x6d, 0x65, 0x61, 0x70, 0x69, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x6b, 0x72, 0x75, 0x69, 0x73, 0x65,
	0x67, 0x61, 0x6d, 0x65, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x61,
	0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x66, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x12, 0x27, 0x2e, 0x6b, 0x72, 0x75, 0x69, 0x73, 0x65, 0x67,
	0x61, 0x6d, 0x65, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x47, 0x61, 0x6d,
	0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x28, 0x2e, 0x6b, 0x72, 0x75, 0x69, 0x73, 0x65, 0x67, 0x61, 0x6d, 0x65, 0x61, 0x70, 0x69, 0x2e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xe0, 0x02, 0x0a, 0x14, 0x47, 0x61,
	0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x66, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x53, 0x65, 0x74, 0x73, 0x12, 0x27, 0x2e, 0x6b, 0x72, 0x75, 0x69, 0x73, 0x65,
	0x67, 0x61, 0x6d, 0x65, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x65, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x28, 0x2e, 0x6b, 0x72, 0x75, 0x69, 0x73, 0x65, 0x67, 0x61, 0x6d, 0x65, 0x61, 0x70, 0x69,
	0x2e, 0x47, 0x65, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x65,
	0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x6f, 0x0a, 0x14, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x65,
	0x74, 0x73, 0x12, 0x2a, 0x2e, 0x6b, 0x72, 0x75, 0x69, 0x73, 0x65, 0x67, 0x61, 0x6d, 0x65, 0x61,
	0x70, 0x69, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x53, 0x65, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b,
	0x2e, 0x6b, 0x72, 0x75, 0x69, 0x73, 0x65, 0x67, 0x61, 0x6d, 0x65, 0x61, 0x70, 0x69, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53,
	0x65, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x6f, 0x0a, 0x14, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53,
	0x65, 0x74, 0x73, 0x12, 0x2a, 0x2e, 0x6b, 0x72, 0x75, 0x69, 0x73, 0x65, 0x67, 0x61, 0x6d, 0x65,
	0x61, 0x70, 0x69, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x53, 0x65, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x2b, 0x2e, 0x6b, 0x72, 0x75, 0x69, 0x73, 0x65, 0x67, 0x61, 0x6d, 0x65, 0x61, 0x70, 0x69, 0x2e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x53, 0x65, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x41, 0x5a, 0x3f,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x43, 0x6c, 0x6f, 0x75, 0x64,
	0x4e, 0x61, 0x74, 0x69, 0x76, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x2f, 0x6b, 0x72, 0x75, 0x69, 0x73,
	0x65, 0x2d, 0x67, 0x61, 0x6d, 0x65, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x66, 0x61, 0x63, 0x61, 0x64,
	0x65, 0x2f, 0x61, 0x70, 0x69, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_kruise_game_api_proto_rawDescOnce sync.Once
	file_kruise_game_api_proto_rawDescData = file_kruise_game_api_proto_rawDesc
)

func file_kruise_game_api_proto_rawDescGZIP() []byte {
	file_kruise_game_api_proto_rawDescOnce.Do(func() {
		file_kruise_game_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_kruise_game_api_proto_rawDescData)
	})
	return file_kruise_game_api_proto_rawDescData
}

var file_kruise_game_api_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_kruise_game_api_proto_goTypes = []interface{}{
	(*GetGameServersRequest)(nil),        // 0: kruisegameapi.GetGameServersRequest
	(*GetGameServersResponse)(nil),       // 1: kruisegameapi.GetGameServersResponse
	(*UpdateGameServersRequest)(nil),     // 2: kruisegameapi.UpdateGameServersRequest
	(*UpdateGameServersResponse)(nil),    // 3: kruisegameapi.UpdateGameServersResponse
	(*UpdateGameServerResult)(nil),       // 4: kruisegameapi.UpdateGameServerResult
	(*DeleteGameServersRequest)(nil),     // 5: kruisegameapi.DeleteGameServersRequest
	(*DeleteGameServersResponse)(nil),    // 6: kruisegameapi.DeleteGameServersResponse
	(*DeleteGameServerResult)(nil),       // 7: kruisegameapi.DeleteGameServerResult
	(*GetGameServerSetsRequest)(nil),     // 8: kruisegameapi.GetGameServerSetsRequest
	(*GetGameServerSetsResponse)(nil),    // 9: kruisegameapi.GetGameServerSetsResponse
	(*UpdateGameServerSetsRequest)(nil),  // 10: kruisegameapi.UpdateGameServerSetsRequest
	(*UpdateGameServerSetsResponse)(nil), // 11: kruisegameapi.UpdateGameServerSetsResponse
	(*UpdateGameServerSetResult)(nil),    // 12: kruisegameapi.UpdateGameServerSetResult
	(*DeleteGameServerSetsRequest)(nil),  // 13: kruisegameapi.DeleteGameServerSetsRequest
	(*DeleteGameServerSetsResponse)(nil), // 14: kruisegameapi.DeleteGameServerSetsResponse
	(*DeleteGameServerSetResult)(nil),    // 15: kruisegameapi.DeleteGameServerSetResult
}
var file_kruise_game_api_proto_depIdxs = []int32{
	4,  // 0: kruisegameapi.UpdateGameServersResponse.results:type_name -> kruisegameapi.UpdateGameServerResult
	7,  // 1: kruisegameapi.DeleteGameServersResponse.results:type_name -> kruisegameapi.DeleteGameServerResult
	12, // 2: kruisegameapi.UpdateGameServerSetsResponse.results:type_name -> kruisegameapi.UpdateGameServerSetResult
	15, // 3: kruisegameapi.DeleteGameServerSetsResponse.results:type_name -> kruisegameapi.DeleteGameServerSetResult
	0,  // 4: kruisegameapi.GameServerService.GetGameServers:input_type -> kruisegameapi.GetGameServersRequest
	2,  // 5: kruisegameapi.GameServerService.UpdateGameServers:input_type -> kruisegameapi.UpdateGameServersRequest
	5,  // 6: kruisegameapi.GameServerService.DeleteGameServers:input_type -> kruisegameapi.DeleteGameServersRequest
	8,  // 7: kruisegameapi.GameServerSetService.GetGameServerSets:input_type -> kruisegameapi.GetGameServerSetsRequest
	10, // 8: kruisegameapi.GameServerSetService.UpdateGameServerSets:input_type -> kruisegameapi.UpdateGameServerSetsRequest
	13, // 9: kruisegameapi.GameServerSetService.DeleteGameServerSets:input_type -> kruisegameapi.DeleteGameServerSetsRequest
	1,  // 10: kruisegameapi.GameServerService.GetGameServers:output_type -> kruisegameapi.GetGameServersResponse
	3,  // 11: kruisegameapi.GameServerService.UpdateGameServers:output_type -> kruisegameapi.UpdateGameServersResponse
	6,  // 12: kruisegameapi.GameServerService.DeleteGameServers:output_type -> kruisegameapi.DeleteGameServersResponse
	9,  // 13: kruisegameapi.GameServerSetService.GetGameServerSets:output_type -> kruisegameapi.GetGameServerSetsResponse
	11, // 14: kruisegameapi.GameServerSetService.UpdateGameServerSets:output_type -> kruisegameapi.UpdateGameServerSetsResponse
	14, // 15: kruisegameapi.GameServerSetService.DeleteGameServerSets:output_type -> kruisegameapi.DeleteGameServerSetsResponse
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_kruise_game_api_proto_init() }
func file_kruise_game_api_proto_init() {
	if File_kruise_game_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_kruise_game_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGameServersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kruise_game_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGameServersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kruise_game_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateGameServersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kruise_game_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateGameServersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kruise_game_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateGameServerResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kruise_game_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteGameServersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kruise_game_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteGameServersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kruise_game_api_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteGameServerResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kruise_game_api_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGameServerSetsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kruise_game_api_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGameServerSetsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kruise_game_api_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateGameServerSetsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kruise_game_api_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateGameServerSetsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kruise_game_api_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateGameServerSetResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kruise_game_api_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteGameServerSetsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kruise_game_api_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteGameServerSetsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kruise_game_api_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteGameServerSetResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_kruise_game_api_proto_msgTypes[4].OneofWrappers = []interface{}{}
	file_kruise_game_api_proto_msgTypes[7].OneofWrappers = []interface{}{}
	file_kruise_game_api_proto_msgTypes[12].OneofWrappers = []interface{}{}
	file_kruise_game_api_proto_msgTypes[15].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kruise_game_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_kruise_game_api_proto_goTypes,
		DependencyIndexes: file_kruise_game_api_proto_depIdxs,
		MessageInfos:      file_kruise_game_api_proto_msgTypes,
	}.Build()
	File_kruise_game_api_proto = out.File
	file_kruise_game_api_proto_rawDesc = nil
	file_kruise_game_api_proto_goTypes = nil
	file_kruise_game_api_proto_depIdxs = nil
}
