apiVersion: apps/v1
kind: Deployment
metadata:
  name: kruise-game-api-server
  labels:
    app: kruise-game-api-server
  namespace: kruise-game-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kruise-game-api-server
  template:
    metadata:
      labels:
        app: kruise-game-api-server
    spec:
      containers:
        - name: kruise-game-api-server
          image: crpi-8cm99ihkk1hz8ju9.cn-shenzhen.personal.cr.aliyuncs.com/scottliu/kruise-game-api-server:v0.0.9
          args:
            - -print-body=true
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /healthz
              port: 8080
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /healthz
              port: 8080
      serviceAccountName: kruise-game-api-sa
