apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kruise-game-api-role
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - list
      - get
  - apiGroups:
      - game.kruise.io
    resources:
      - gameservers
      - gameserversets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - game.kruise.io
    resources:
      - gameservers/status
      - gameserversets/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: kruise-game-api-sa
  namespace: kruise-game-system

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kruise-game-api-rolebinding
  namespace: kruise-game-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kruise-game-api-role
subjects:
  - kind: ServiceAccount
    name: kruise-game-api-sa
    namespace: kruise-game-system
