apiVersion: v1
kind: Service
metadata:
  name: kruise-game-api-server
  namespace: kruise-game-system
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: kruise-game-api-server
